name: to_do_app
description: "ToDo App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  easy_date_timeline: ^1.1.3
  provider: ^6.1.2
  animated_custom_dropdown: 3.1.1
  shared_preferences: ^2.3.2


  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  flutter_easyloading: ^3.0.5
  bot_toast: ^4.1.3
  lottie: ^3.1.2
  flutter_slidable: ^3.1.1
  firebase_auth: ^5.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-Light.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf